tiny changes for alignment tests
biopet/biopet-functional-tests pull request #19
Opened 2017-06-01 12:15 UTC by akaljuvee

2017-06-06 10:31 UTC, ffinfo requested changes

2017-06-06 10:31 UTC, ffinfo commented on .gitmodules
> +	branch = fix-BIOPET-697
Could you switch this back to master again? it's already merge there now

2017-06-06 10:31 UTC, ffinfo commented on Mapping/pom.xml
> +            <artifactId>BiopetExtensions</artifactId>
Why you need this dependency? If possible I would prefer to do it with this dependency. This because this is not stable.

2017-06-06 10:31 UTC, ffinfo commented on Mapping/src/test/scala/nl/lumc/sasc/biopet/test/mapping/MappingSingle.scala
> +  override def configs = {
You know this happens: `trait MappingPaired extends MappingSingle`

2017-06-06 10:31 UTC, ffinfo commented on Mapping/src/test/scala/nl/lumc/sasc/biopet/test/mapping/MappingSingle.scala
> +    val programs: List[String] = CollectMultipleMetrics.Programs.values.toList.collect({
Been thinking about this, we should remove this and fix this inside biopet, this is just a workaround for something we can fix ourselfs

2017-06-06 10:33 UTC, akaljuvee commented on Mapping/pom.xml
> +            <artifactId>BiopetExtensions</artifactId>
inorder to have the enum CollectMultipleMetrics.Programs

2017-06-06 10:33 UTC, akaljuvee commented on Mapping/src/test/scala/nl/lumc/sasc/biopet/test/mapping/MappingSingle.scala
> +  override def configs = {
yes, I know and this config file gets removed for Paired tests

2017-06-06 10:35 UTC, akaljuvee commented on Mapping/src/test/scala/nl/lumc/sasc/biopet/test/mapping/MappingSingle.scala
> +    val programs: List[String] = CollectMultipleMetrics.Programs.values.toList.collect({
yes, I've made an issue for this, BIOPET-703

2017-06-07 11:04 UTC, ffinfo approved these changes

2017-06-08 09:47 UTC, merged