Fix biopet 608
biopet/biopet-functional-tests pull request #7
Opened 2017-03-23 08:54 UTC by akaljuvee

2017-04-11 18:08 UTC, ffinfo requested changes

2017-04-11 18:08 UTC, ffinfo commented on Common/src/main/scala/nl/lumc/sasc/biopet/test/samples/NA12878WGS.scala
> +  val libraries = readJsonFile(config).get("samples")
there is a method in nl.lumc.sasc.biopet.utils.ConfigUtils that is doing this. So this means this method is duplicated.

2017-04-11 18:08 UTC, ffinfo commented on Shiva/src/test/scala/nl/lumc/sasc/biopet/test/shiva/ShivaFunctional.scala
> +  val svCallers: List[String] = ShivaSvCalling.getSvCallersAsStrList(List(new Breakdancer, new Delly))
Clever is working in the current develop branch. Could you add this in again?

ps: was waiting on this change to look into this PR ;)

2017-04-11 18:08 UTC, ffinfo commented on Shiva/src/test/scala/nl/lumc/sasc/biopet/test/shiva/ShivaFunctional.scala
> +  override def memoryArg = "-Xmx4G"
Not sure with the current summary this is still needed

2017-04-11 18:08 UTC, ffinfo commented on Shiva/src/test/scala/nl/lumc/sasc/biopet/test/shiva/ShivaFunctional.scala
> +
We should also add a dbsnp file to this run.

2017-04-12 16:13 UTC, akaljuvee commented
ok, I'm ready with these things now

2017-04-19 07:40 UTC, rhpvorderman approved these changes

2017-04-28 17:32 UTC, ffinfo approved these changes

2017-04-28 17:37 UTC, merged